import 'react-app-polyfill/ie11';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Tree } from '../src/index';

const App = () => {
  const nodes = {
    '001': {
      _key: '001',
      name: '項目管理',
      father: '',
      sortList: ['002', '003', '004', '005'],
      contract: false,
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '002': {
      _key: '002',
      name: '計劃進度',
      father: '001',
      sortList: ['006', '007'],
      contract: false,
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '003': {
      _key: '003',
      name: '項目狀態',
      father: '001',
      sortList: ['010', '011'],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '004': {
      _key: '004',
      name: '項目會議',
      father: '001',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '005': {
      _key: '005',
      name: '驗收',
      father: '001',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '006': {
      _key: '006',
      name: '階段壹',
      father: '002',
      contract: false,
      sortList: ['008', '009'],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '007': {
      _key: '007',
      name: '階段二',
      father: '002',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '008': {
      _key: '008',
      name: '備份json文件',
      father: '006',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '009': {
      _key: '009',
      name: '還原數據',
      father: '006',
      sortList: ['015'],
      showAvatar: true,
      showCheckbox: true,
      checked: false,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '010': {
      _key: '010',
      name: '4月計劃',
      father: '003',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '011': {
      _key: '011',
      name: '5月計劃',
      father: '003',
      sortList: ['012', '013', '014'],
      contract: false,
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '012': {
      _key: '012',
      name: '原型、界面設計',
      father: '011',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '013': {
      _key: '013',
      name: '開發',
      father: '011',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '014': {
      _key: '014',
      name: '測試',
      father: '011',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
    '015': {
      _key: '015',
      name: '還原數據-還原數據',
      father: '009',
      sortList: [],
      showAvatar: true,
      showCheckbox: true,
      checked: true,
      showStatus: true,
      hour: 0.1,
      limitDay: 1610726400000,
    },
  };
  return (
    <div>
      <Tree nodes={nodes} startId="001" />
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
