name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      # - name: Test
      #   run: yarn test --ci --coverage --maxWorkers=2
      #   env:
      #     CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      # - name: Publish
      #     run: yarn publish
      #     env:
      #       NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build storybook
        run: yarn build-storybook
        env:
          CI: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
