# https://github.com/marketplace/actions/remove-artifacts
name: Remove old artifacts

on:
  # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows
  schedule:
    # 每周六的UTC17点
    - cron: '0 17 * * 0'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '5 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5
