import React, { useRef } from 'react';
import { MenuTree, MenuProps } from '../src';
import { Meta, Story } from '@storybook/react';

const nodes = {
  '001': {
    _key: '001',
    name: '項目管理',
    father: '',
    sortList: ['002', '003', '004', '005'],
    contract: false,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: -23,
  },
  '002': {
    _key: '002',
    name: '計劃進度',
    father: '001',
    sortList: ['006', '007'],
    contract: false,
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: -23,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '003': {
    _key: '003',
    name: '項目狀態',
    father: '001',
    sortList: ['010', '011'],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/mET1O2e6I8jrs4M.png',
  },
  '004': {
    _key: '004',
    name: '項目會議',
    father: '001',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '005': {
    _key: '005',
    name: '驗收',
    father: '001',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '006': {
    _key: '006',
    name: '階段壹',
    father: '002',
    contract: false,
    sortList: ['008', '009'],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '007': {
    _key: '007',
    name: '階段二',
    father: '002',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '008': {
    _key: '008',
    name: '備份json文件',
    father: '006',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/mET1O2e6I8jrs4M.png',
  },
  '009': {
    _key: '009',
    name: '還原數據',
    father: '006',
    sortList: ['015'],
    showAvatar: false,
    showCheckbox: false,
    checked: false,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '010': {
    _key: '010',
    name: '4月計劃',
    father: '003',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '011': {
    _key: '011',
    name: '5月計劃',
    father: '003',
    sortList: ['012', '013', '014'],
    contract: false,
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/4SFsZLDU8bdWjGR.png',
  },
  '012': {
    _key: '012',
    name: '原型、界面設計',
    father: '011',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/mET1O2e6I8jrs4M.png',
  },
  '013': {
    _key: '013',
    name: '開發',
    father: '011',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/mET1O2e6I8jrs4M.png',
  },
  '014': {
    _key: '014',
    name: '測試',
    father: '011',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/mET1O2e6I8jrs4M.png',
  },
  '015': {
    _key: '015',
    name: '還原數據-還原數據',
    father: '009',
    sortList: [],
    showAvatar: false,
    showCheckbox: false,
    checked: true,
    showStatus: false,
    hour: 0.1,
    limitDay: 2,
    icon: 'https://i.loli.net/2020/10/15/mET1O2e6I8jrs4M.png',
  },
};

const meta: Meta = {
  title: 'Tree(Menu)',
  component: MenuTree,
  parameters: {
    controls: { expanded: true },
  },
};

export default meta;

const Template: Story<MenuProps> = args => {
  const treeRef = useRef(null);
  return (
    <div>
      <MenuTree {...args} />
    </div>
  );
};

export const Default = Template.bind({});
Default.args = {
  nodes: nodes,
  startId: '001',
  // showNodeOptions: true,
};
